name: Main Pipeline
run-name: ${{ github.actor }} is running GitHub Actions ğŸš€
on: [push]
jobs:

  Init:
    runs-on: ubuntu-latest
    steps:

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  
  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build www
        working-directory: ./www
        run: ./gradlew build --no-daemon

      - name: Export www app artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: www-app-jar
          path: ./www/build/libs/www-app.jar
          if-no-files-found: error

      - name: Build api
        working-directory: ./api
        run: ./gradlew build --no-daemon

      - name: Export api app artifact (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: api-app-jar
          path: ./api/build/libs/api-app.jar
          if-no-files-found: error


