name: Main Pipeline
run-name: ${{ github.actor }} is running GitHub Actions ğŸš€
on: [push]
jobs:

  Init:
    runs-on: ubuntu-latest
    steps:

      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  
  Build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Make gradlew executable
        run: |
          chmod +x ./www/gradlew
          chmod +x ./api/gradlew

      - name: Build www
        working-directory: ./www
        run: ./gradlew build --no-daemon

      - name: Build api
        working-directory: ./api
        run: ./gradlew build --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push www-server-image
        uses: docker/build-push-action@v6
        with:
          context: ./www
          push: true
          tags: user/www-server-image:latest

      - name: Build and push api-server-iamge
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: user/api-server-image:latest


        
      

